/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simbrain_special_projects_plasticity_proj_IPIFRule */

#ifndef _Included_org_simbrain_special_projects_plasticity_proj_IPIFRule
#define _Included_org_simbrain_special_projects_plasticity_proj_IPIFRule
#ifdef __cplusplus
extern "C" {
#endif
#undef org_simbrain_special_projects_plasticity_proj_IPIFRule_MAX_DIGITS
#define org_simbrain_special_projects_plasticity_proj_IPIFRule_MAX_DIGITS 9L
#undef org_simbrain_special_projects_plasticity_proj_IPIFRule_DEFAULT_INCREMENT
#define org_simbrain_special_projects_plasticity_proj_IPIFRule_DEFAULT_INCREMENT 0.1
/*
 * Class:     org_simbrain_special_projects_plasticity_proj_IPIFRule
 * Method:    gaussConv
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_simbrain_special_1projects_plasticity_1proj_IPIFRule_gaussConv
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
