/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule */

#ifndef _Included_org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule
#define _Included_org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule
#ifdef __cplusplus
extern "C" {
#endif
#undef org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule_MAX_DIGITS
#define org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule_MAX_DIGITS 9L
/*
 * Class:     org_simbrain_special_projects_plasticity_proj_ModifiedBCMRule
 * Method:    gaussConv
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_org_simbrain_special_1projects_plasticity_1proj_ModifiedBCMRule_gaussConv
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
